inherit_from:
  - .rubocop_todo.yml

inherit_gem:
  rswag-specs: .rubocop_rspec_alias_config.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
  - rubocop-rails
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
    - 'Rakefile'
    - 'config.ru'    

Style/Documentation:
  Enabled: false

# Stick to "indented_relative_to_receiver" as it's better for keeping line length short yet still readable
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

# Metrics/BlockLength rule is not applicable for DSLs, like spec files or routes
Metrics/BlockLength:
  Exclude:

RSpec/DescribedClassModuleWrapping:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# NOTE: X-API-KEY has to be excluded because we need to name "let" this way to make rswag work.
RSpec/VariableName:
  Enabled: true
  AllowedPatterns:
    - X-API-KEY
    - X-API-VERSION
    - Authorization
    - Content-Type

# NOTE: Let rubocop know about rswag DSL
# Details: https://github.com/rubocop/rubocop-rspec/issues/1077
RSpec:
  Language:
    Includes:
      Examples:
        - response
